# Generated by Django 3.0.2 on 2020-12-01 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(choices=[('Dapartment', (('Biotechnology', 'Biotechnology'), ('Botany', 'Botany'), ('Chemestry', 'Chemestry'), ('Commerce', 'Commerce'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('Education', 'Education'), ('English', 'English'), ('History', 'History'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Political Science', 'Political Science'), ('Socialogy', 'Socialogy'), ('Social Work', 'Social Work'), ('Zoology', 'Zoology'), ('PG', 'PG'))), ('Clubs', (('AICUF', 'AICUF'), ('BSSM', 'BSSM'), ('Campus Ministry', 'Campus Ministry'), ('Cultural Club', 'Cultural Club'), ('Debating Society', 'Debating Society'), ('Electoral Literacy Cell', 'Electoral Literacy Cell'), ('IT Club', 'IT Club'), ('Jesus Youth', 'Jesus Youth'), ('Maram Times', 'Maram Times'), ('Media Club', 'Media Club'), ('Music Club', 'Music Club'), ('Nature Club', 'Nature Club'), ('NSS', 'NSS'), ('Poetry Club', 'Poetry Club'), ('Red Ribbon', 'Red Ribbon'), ('Rovers and Rangers', 'Rovers and Rangers'), ('Science Club', 'Science Club'), ('Speech Club', 'Speech Club'), ('Sports Club', 'Sports Club'), ('Story Telling Club', 'Story Telling Club'), ('Women Cell', 'Women Cell'))), ('Others', (('Sports Week', 'Sports Week'), ('Teachers Day', 'Teachers Day'), ('Exams', 'Exams'), ('Others', 'Others')))], default='Others', max_length=25)),
                ('img', models.ImageField(upload_to='image')),
            ],
        ),
    ]
